"""Add correlation storage

Revision ID: 44694df23e05
Revises: c2bd8d557391
Create Date: 2026-06-14 14:07:36.362331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44694df23e05'
down_revision: Union[str, Sequence[str], None] = 'c2bd8d557391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('time_window', sa.Integer(), nullable=False),
    sa.Column('severity_weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_rules_id'), 'correlation_rules', ['id'], unique=False)
    op.create_table('correlation_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('matched_events', sa.JSON(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('match_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_score', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['correlation_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_matches_correlation_score'), 'correlation_matches', ['correlation_score'], unique=False)
    op.create_index('ix_correlation_matches_created_at', 'correlation_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_correlation_matches_expires_at'), 'correlation_matches', ['expires_at'], unique=False)
    op.create_index(op.f('ix_correlation_matches_id'), 'correlation_matches', ['id'], unique=False)
    op.create_index(op.f('ix_correlation_matches_match_timestamp'), 'correlation_matches', ['match_timestamp'], unique=False)
    op.create_index(op.f('ix_correlation_matches_rule_id'), 'correlation_matches', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correlation_matches_rule_id'), table_name='correlation_matches')
    op.drop_index(op.f('ix_correlation_matches_match_timestamp'), table_name='correlation_matches')
    op.drop_index(op.f('ix_correlation_matches_id'), table_name='correlation_matches')
    op.drop_index(op.f('ix_correlation_matches_expires_at'), table_name='correlation_matches')
    op.drop_index('ix_correlation_matches_created_at', table_name='correlation_matches')
    op.drop_index(op.f('ix_correlation_matches_correlation_score'), table_name='correlation_matches')
    op.drop_table('correlation_matches')
    op.drop_index(op.f('ix_correlation_rules_id'), table_name='correlation_rules')
    op.drop_table('correlation_rules')
    # ### end Alembic commands ###
