"""Add Policy and PolicyEvaluation models

Revision ID: 7f6ccd8a33ee
Revises: 44694df23e05
Create Date: 2026-06-14 14:49:20.833369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6ccd8a33ee'
down_revision: Union[str, Sequence[str], None] = '44694df23e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('OBSERVE', 'NOTIFY', 'REVIEW_REQUIRED', 'FUTURE_MITIGATION', name='policyaction'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('condition_risk_min', sa.Integer(), nullable=True),
    sa.Column('condition_risk_max', sa.Integer(), nullable=True),
    sa.Column('condition_classification', sa.String(), nullable=True),
    sa.Column('condition_status', sa.Enum('NEW', 'UNDER_REVIEW', 'POLICY_EVALUATED', 'DISMISSED', 'RESOLVED', name='observationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index('ix_policies_is_active', 'policies', ['is_active'], unique=False)
    op.create_index('ix_policies_priority', 'policies', ['priority'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'POLICY_EVALUATED', 'DISMISSED', 'RESOLVED', name='observationstatus'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('policy_action', sa.Enum('OBSERVE', 'NOTIFY', 'REVIEW_REQUIRED', 'FUTURE_MITIGATION', name='policyaction'), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['correlation_id'], ['correlation_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_correlation_id'), 'observations', ['correlation_id'], unique=True)
    op.create_index('ix_observations_created_at', 'observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_observations_id'), 'observations', ['id'], unique=False)
    op.create_index('ix_observations_risk_score', 'observations', ['risk_score'], unique=False)
    op.create_index('ix_observations_status', 'observations', ['status'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decision_reason', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('OBSERVE', 'NOTIFY', 'REVIEW_REQUIRED', 'FUTURE_MITIGATION', name='policyaction'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluations_id'), 'policy_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_observation_id'), 'policy_evaluations', ['observation_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_policy_id'), 'policy_evaluations', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_evaluations_policy_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_observation_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index('ix_observations_status', table_name='observations')
    op.drop_index('ix_observations_risk_score', table_name='observations')
    op.drop_index(op.f('ix_observations_id'), table_name='observations')
    op.drop_index('ix_observations_created_at', table_name='observations')
    op.drop_index(op.f('ix_observations_correlation_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_policies_priority', table_name='policies')
    op.drop_index('ix_policies_is_active', table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
