"""create automation tables

Revision ID: fc4fe36e4537
Revises: 351e7f60fff9
Create Date: 2026-06-16 01:10:49.888477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4fe36e4537'
down_revision: Union[str, Sequence[str], None] = '351e7f60fff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.Enum('OBSERVATION', 'INCIDENT', 'EVIDENCE', 'AUDIT', 'EXECUTIVE_SUMMARY', name='reporttype'), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('audit_references', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_created_at', 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index('ix_reports_type', 'reports', ['report_type'], unique=False)
    op.create_table('automation_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('NOTIFY_WEBHOOK', 'CREATE_TICKET', 'SEND_EMAIL', 'LOG_ACTION', name='automationaction'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='automationstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_requests_created_at', 'automation_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_requests_id'), 'automation_requests', ['id'], unique=False)
    op.create_index('ix_automation_requests_policy_id', 'automation_requests', ['policy_id'], unique=False)
    op.create_index('ix_automation_requests_state', 'automation_requests', ['state'], unique=False)
    op.create_table('compliance_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_mappings_framework', 'compliance_mappings', ['framework'], unique=False)
    op.create_index(op.f('ix_compliance_mappings_id'), 'compliance_mappings', ['id'], unique=False)
    op.create_index('ix_compliance_mappings_report', 'compliance_mappings', ['report_id'], unique=False)
    op.create_table('automation_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='automationstate'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['automation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_executions_id'), 'automation_executions', ['id'], unique=False)
    op.create_index('ix_automation_executions_request_id', 'automation_executions', ['request_id'], unique=False)
    op.create_index('ix_automation_executions_started_at', 'automation_executions', ['started_at'], unique=False)
    op.create_index('ix_automation_executions_state', 'automation_executions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automation_executions_state', table_name='automation_executions')
    op.drop_index('ix_automation_executions_started_at', table_name='automation_executions')
    op.drop_index('ix_automation_executions_request_id', table_name='automation_executions')
    op.drop_index(op.f('ix_automation_executions_id'), table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index('ix_compliance_mappings_report', table_name='compliance_mappings')
    op.drop_index(op.f('ix_compliance_mappings_id'), table_name='compliance_mappings')
    op.drop_index('ix_compliance_mappings_framework', table_name='compliance_mappings')
    op.drop_table('compliance_mappings')
    op.drop_index('ix_automation_requests_state', table_name='automation_requests')
    op.drop_index('ix_automation_requests_policy_id', table_name='automation_requests')
    op.drop_index(op.f('ix_automation_requests_id'), table_name='automation_requests')
    op.drop_index('ix_automation_requests_created_at', table_name='automation_requests')
    op.drop_table('automation_requests')
    op.drop_index('ix_reports_type', table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index('ix_reports_created_at', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
